# Site settings
title: RumahWebDesign
header-img: img/home-bg.jpg
email: syahrul110100@gmail.com
copyright_name: RumahWebDesign
description: "Made from Dream"
baseurl: "/blog"
url: "https://rwd.github.io"
twitter_username: syahrul110100
github_username:  alungopal
facebook_username:  alung
email_username:  chiefeorwd@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
